stages:
  - build
  - test
  - deploy

variables:
  PYTHON_VERSION: "3.11.4"
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.pip_cache"
  POETRY_CACHE_DIR: "$CI_PROJECT_DIR/.poetry_cache"
  PIP_NO_CACHE_DIR: "false"

cache:
  paths:
    - ${PIP_CACHE_DIR}
    - ${POETRY_CACHE_DIR}

build_job:
  stage: build
  image: python:${PYTHON_VERSION}-slim
  script:
    - python -m venv .venv
    - source .venv/bin/activate
    - pip install --upgrade pip
    - pip install -r requirements.txt
    - echo "Build stage complete. Dependencies installed."
  artifacts:
    paths:
      - .venv/
    expire_in: 1 hour

test_job:
  stage: test
  image: python:${PYTHON_VERSION}-slim
  needs: 
    - build_job
  script:
    - source .venv/bin/activate
    - pip install --upgrade pip
    - pip install -r requirements.txt
    - echo "Running tests..."
    - pytest --cov=src --cov-report=xml --junitxml=junit.xml
    - echo "Running black code formatter check..."
    - black --check src/
    - echo "Running flake8 code style check..."
    - pip install flake8
    - flake8 src/
    - echo "Tests and code checks complete."
  artifacts:
    reports:
      junit: junit.xml
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
    paths:
      - coverage.xml
    expire_in: 1 day

deploy_job:
  stage: deploy
  image: alpine/git
  needs:
    - test_job
  script:
    - echo "Triggering Render deployment..."
    - apk add --no-cache curl
    - curl -X POST ${RENDER_DEPLOY_HOOK}
    - echo "Render deployment triggered."
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
      when: on_success 
