"""Add indexes to models

Revision ID: 392fa8520a17
Revises: ac2ecae5f28f
Create Date: 2025-06-12 19:38:52.907436

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '392fa8520a17'
down_revision: Union[str, None] = 'ac2ecae5f28f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_assessment_result_assessment_id', 'assessment_results', ['assessment_id'], unique=False)
    op.create_index('idx_assessment_result_user_id', 'assessment_results', ['user_id'], unique=False)
    op.create_index('idx_assessment_course_id', 'assessments', ['course_id'], unique=False)
    op.create_index('idx_content_course_id', 'content', ['course_id'], unique=False)
    op.create_index('idx_course_title', 'courses', ['title'], unique=False)
    op.create_index('idx_course_url', 'courses', ['url'], unique=False)
    op.create_index('idx_interaction_content_id', 'interactions', ['content_id'], unique=False)
    op.create_index('idx_interaction_type', 'interactions', ['interaction_type'], unique=False)
    op.create_index('idx_interaction_user_id', 'interactions', ['user_id'], unique=False)
    op.create_index('idx_learning_progress_course_id', 'learning_progress', ['course_id'], unique=False)
    op.create_index('idx_learning_progress_user_course', 'learning_progress', ['user_id', 'course_id'], unique=True)
    op.create_index('idx_learning_progress_user_id', 'learning_progress', ['user_id'], unique=False)
    op.create_index('idx_user_email', 'users', ['email'], unique=False)
    op.create_index('idx_user_username', 'users', ['username'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_user_username', table_name='users')
    op.drop_index('idx_user_email', table_name='users')
    op.drop_index('idx_learning_progress_user_id', table_name='learning_progress')
    op.drop_index('idx_learning_progress_user_course', table_name='learning_progress')
    op.drop_index('idx_learning_progress_course_id', table_name='learning_progress')
    op.drop_index('idx_interaction_user_id', table_name='interactions')
    op.drop_index('idx_interaction_type', table_name='interactions')
    op.drop_index('idx_interaction_content_id', table_name='interactions')
    op.drop_index('idx_course_url', table_name='courses')
    op.drop_index('idx_course_title', table_name='courses')
    op.drop_index('idx_content_course_id', table_name='content')
    op.drop_index('idx_assessment_course_id', table_name='assessments')
    op.drop_index('idx_assessment_result_user_id', table_name='assessment_results')
    op.drop_index('idx_assessment_result_assessment_id', table_name='assessment_results')
    # ### end Alembic commands ###
