"""Add url to Course model

Revision ID: ac2ecae5f28f
Revises: 62d8e5bba881
Create Date: 2025-06-12 17:01:51.330506

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac2ecae5f28f'
down_revision: Union[str, None] = '62d8e5bba881'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('url', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'courses', ['url'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'courses', type_='unique')
    op.drop_column('courses', 'url')
    # ### end Alembic commands ###
