"""Add course detail columns

Revision ID: c3f651551176
Revises: 392fa8520a17
Create Date: 2025-06-14 00:36:05.137893

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c3f651551176"
down_revision: Union[str, None] = "392fa8520a17"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("courses", sa.Column("instructor", sa.String(), nullable=True))
    op.add_column("courses", sa.Column("price", sa.Float(), nullable=True))
    op.add_column("courses", sa.Column("currency", sa.String(), nullable=True))
    op.add_column("courses", sa.Column("difficulty", sa.String(), nullable=True))
    op.add_column("courses", sa.Column("category", sa.String(), nullable=True))
    op.add_column("courses", sa.Column("platform", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("courses", "platform")
    op.drop_column("courses", "category")
    op.drop_column("courses", "difficulty")
    op.drop_column("courses", "currency")
    op.drop_column("courses", "price")
    op.drop_column("courses", "instructor")
    # ### end Alembic commands ###
