"""Remove email column from User model

Revision ID: c5ef93741107
Revises: c3f651551176
Create Date: 2025-06-14 02:27:47.862940

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5ef93741107'
down_revision: Union[str, None] = 'c3f651551176'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('user_identifier', sa.String(), nullable=False))
    op.drop_index(op.f('idx_user_email'), table_name='users')
    op.drop_index(op.f('idx_user_username'), table_name='users')
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.drop_constraint(op.f('users_username_key'), 'users', type_='unique')
    op.create_index('idx_user_user_identifier', 'users', ['user_identifier'], unique=False)
    op.create_unique_constraint(None, 'users', ['user_identifier'])
    op.drop_column('users', 'email')
    op.drop_column('users', 'username')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_index('idx_user_user_identifier', table_name='users')
    op.create_unique_constraint(op.f('users_username_key'), 'users', ['username'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_user_username'), 'users', ['username'], unique=False)
    op.create_index(op.f('idx_user_email'), 'users', ['email'], unique=False)
    op.drop_column('users', 'user_identifier')
    # ### end Alembic commands ###
